<h2>Brief description of the classes</h2>
<ul>
	<li><a href="../doc/js_docs_out/DHTMLSuite.config.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.config</a> - Used to set system paths(css, images) etc.</li>
	<li>DHTMLSuite.globalVariableStorage - Used to store global variables used by widgets.</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.common.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.common</a> - Common methods used by more than one script, examples: loadCss, setCookie,getCookie</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.clientInfo.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.clientInfo</a> - Stores client/browser information</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.tableWidgetPageHandler.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.tableWidgetPageHandler</a> - Widget used to create page navigation links for table widgets.</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.tableWidget.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.tableWidget</a> - Class for the table widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.dragDrop.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.dragDrop</a> - Class used to make web page elements dragable</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.tabView.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.tabView</a> - Tab view widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.JSDragDropTree.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.JSDragDropTree</a> - Folder tree with drag and drop</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.dynamicContent.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.dynamicContent</a> - Class used to get content from the server(AJAX). </li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.colorHelp.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.colorHelp</a> - Contains color convertion methods. example: RGB->HSV</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.slider.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.slider</a> - Slider widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.modalMessage.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.modalMessage</a> - Modal message widget.</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.dynamicTooltip.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.dynamicTooltip</a> - Ajax tooltip widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.infoPanel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.infoPanel</a> - Info panel widget. Creates a panel with collapse/expand features.</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.progressBar.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.progressBar</a> - Progress bar widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.menuModelItem.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.menuModelItem</a> - Data source("Model") for menu items</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.menuModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.menuModel</a> - Data source("Model") for a menu(collection of menu items)</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.menuItem.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.menuItem</a> - Menu item widget("View" and "Controller" for menu items)</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.menuBar.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.menuBar</a> - Menu bar widget. Contains a collection of menuItem objects</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.windowDataModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.windowDataModel</a> - Data model for window widget (NOT YET IMPLEMENTED)</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.windowDataModelContent.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.windowDataModelContent</a> - Data model for window content (NOT YET IMPLEMENTED)</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.paneSplitterModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.paneSplitterModel</a> - Data source("Model") for the pane splitter</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.paneSplitterPaneModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.paneSplitterPaneModel</a> - Data source("Model") for a pane</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.paneSplitterContentModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.paneSplitterContentModel</a> - Data source("Model") for content inside a pane</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.paneSplitterPane.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.paneSplitterPane</a> - View and controller for a pane</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.paneSplitter.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.paneSplitter</a> - The pane splitter widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.listModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.listModel</a> - Stores an array of value and text</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.textEditModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.textEditModel</a> - Data source("Model") for the Inline text edit widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.textEdit.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.textEdit</a> - The inline text edit widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.contextMenu.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.contextMenu</a> - Context menu widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.imageEnlarger.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.imageEnlarger</a> - Image enlarger widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.windowModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.windowModel</a> - "Model" for the window widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.windowTabModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.windowModel</a> - "Model" for window tabs</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.windowWidget.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.windowWidget</a> - Window widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.calendar.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.calendar</a> - Calendar widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.calendarModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.calendarModel</a> - "Model for the calendar widget"</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.calendarLanguageModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.calendarLanguageModel</a> - Language data for the calendar widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.calendarLanguageModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.calendarLanguageModel</a> - Language data for the calendar widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.colorUtil.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.colorUtil</a> - Color methods</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.colorWidget.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.colorWidget </a> - Color widget/Color picker</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.colorPalette.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.colorPalette </a> - Color palette widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.floatingGallery.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.floatingGallery </a> - Floating gallery widget</li>
	<li><a href="../doc/js_docs_out/DHTMLSuite.imageSelection.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.imageSelection </a> - Image selection widget</li>
</ul>
<h2>Method names</h2>
<p>Javascript doesn't support private and public variables and methods. To distinguish between private and public methods, I have added two underscores(__) as prefixes to all "private methods". These methods
should never be called by your scripts, only by the DHTML Suite it's self. If you need access to a private method, please use the forum to suggest a new public method. Private methods may be changed later on, public
methods won't. That's why this is so important. If you're refering to a private method in your code, your application might break later on if/when changes is been made to that method.</p>