<p>Classes used:</p>
<ul>
	<li><b><a href="../doc/js_docs_out/DHTMLSuite.calendar.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.calendar</a></b> - Main class for the widget.</li>
	<li><b><a href="../doc/js_docs_out/DHTMLSuite.calendarModel.html" onclick="var scriptDocWin=window.open(this.href);return false">DHTMLSuite.calendarModel</a></b> - Handle calendar data.</li>
</ul>
<p>Demo: </p>
<ul>
	<li><a href="demo-calendar-1.html" onclick="var demoWin=window.open(this.href);return false">demo-calendar-1.html</a></li>
</ul>
<p>Default css file: <a href="../css_dhtmlsuite/calendar.css" onclick="var demoWin=window.open(this.href);return false">css_dhtmlsuite/calendar.css</a></p>


